# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  ${TOPDIR}/../sources/poky/meta \
  ${TOPDIR}/../sources/poky/meta-poky \
  ${TOPDIR}/../sources/poky/meta-yocto-bsp \
  ${TOPDIR}/../sources/meta-freescale \
  ${TOPDIR}/../sources/meta-openembedded \ 
  ${TOPDIR}/../sources/meta-qoriq \ 
  ${TOPDIR}/../sources/meta-selinux \ 
  ${TOPDIR}/../sources/meta-virtualization \ 
  ${TOPDIR}/../sources/meta-browser \ 
  ${TOPDIR}/../sources/meta-cloud-services \ 
  ${TOPDIR}/../sources/meta-freescale-distro \ 
  "
