# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-monogateway"
BBFILE_PATTERN_meta-monogateway := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-monogateway = "10"
LAYERSERIES_COMPAT_meta-monogateway = "walnascar"

# Add the licenses into the metadata
LICENSE_PATH += "${LAYERDIR}/custom-licenses"

FSL_EULA_FILE = "${LAYERDIR}/EULA"