require conf/distro/mono-sdk.conf

DISTRO = "gatewayos"
DISTRO_NAME = "Gateway Linux Distribution"
DISTRO_VERSION = "1.0"

# Use systemd as init manager
INIT_MANAGER = "systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"

# Distro features
DISTRO_FEATURES = " inetutils pulseaudio i2c-tools curl gzip nano apache2 alsa-lib alsa-utils nano usbutils"